### ISSUE TITLE
Canvas note loses colors when scrolling too far down

### ISSUE THREAD

**Issue by BillyCottrell** [code-of-chaos/obsidian-colored_tags_wrangler#26] opened 2023-12-11 12:13 UTC
Let's say I make a note like this:

![image](https://github.com/code-of-chaos/obsidian-colored_tags_wrangler/assets/32330318/f0001b02-1a43-4c80-9af4-bd3bc8e07d81)

If I scroll down it loses those colors:

![Obsidian_VdXWuQv9wC](https://github.com/code-of-chaos/obsidian-colored_tags_wrangler/assets/32330318/844a5078-0872-4c19-9106-58fa26dd3780)

but if i scroll up again I gain the colors before the tag becomes visible:

![Obsidian_ZTSCnMovvA](https://github.com/code-of-chaos/obsidian-colored_tags_wrangler/assets/32330318/6680818d-adf0-447b-b5ac-0ff95572837b)

I think that this occurs because the tag gets unloaded as I scroll down and then loads back in when scrolling back up.

Dunno if this can be fixed or not, but I'd thought I'd let you know of this visual glitch.

Hope you can fix this! 😉

**Comment by AnnaSasDev** [comment] 2023-12-11 12:18
tied to #18 , not a duplicated but will probably be solved together

**Comment by AnnaSasDev** [comment] 2024-01-02 15:23
This is a duplicate of the core issue of #18 .

**Closed as completed by AnnaSasDev** 2024-01-02 15:23 UTC
Labels: bug, duplicate
