### ISSUE TITLE
Enhancement: Ability to rearrange order of Custom Color Tags

### ISSUE THREAD

**Issue by bubonicfred** [code-of-chaos/obsidian-colored_tags_wrangler#31] opened 2023-12-22 01:53 UTC
I've used colors on tags as well as nested tags for a while to label various notes in graph mode, the order here is rather important.
I would like to be able to reorder the tags as I can in graph mode (by dragging the color picker circle).

Being able to copy and or paste the settings from/to graph mode would be nice, but I have no idea how possible that is.

**Comment by AnnaSasDev** [comment] 2023-12-23 18:04
> I've used colors on tags as well as nested tags for a while to label various notes in graph mode, the order here is rather important.
> I would like to be able to reorder the tags as I can in graph mode (by dragging the color picker circle).

A rework of the tags in the settings is already being planned, with the enhancement you said 😄 
The issue is, as far as I know I'll have to build a custom solution, and also have it work on mobile...

> Being able to copy and or paste the settings from/to graph mode would be nice, but I have no idea how possible that is.

I honestly hadn't even thought about this. I'll look into it!

**Comment by AnnaSasDev** [comment] 2024-01-02 14:54
The tags in settings will be able to be re-orderd by simple buttons next to the color pickers.

The graph mode was a little harder to figure out. I've implemented two approaches, both by commands.
The first is a simple "place code block at carret", and writes the entire tags list as a colorGroup list to a code block in your note. The other (more experimental) option is to immediatly overwrite the graph.json file with the colorGroups. This is only available on desktop and is clearly marked as a EXPERIMENTAL feature haha. Hope the first option will help a lot @bubonicfred , when PR #32 is done

**Comment by AnnaSasDev** [comment] 2024-01-02 14:55
Snippet of new caret system:
![image](https://github.com/code-of-chaos/obsidian-colored_tags_wrangler/assets/74367457/d9a00160-f8f5-42d2-9e90-acd13832c3ca)


Snippet of the code block written:
![image](https://github.com/code-of-chaos/obsidian-colored_tags_wrangler/assets/74367457/56d9c4a7-9a4a-44b0-bbd7-79d35c194191)

**Comment by AnnaSasDev** [comment] 2024-01-02 15:03
(These experimental commands have to be enabled in the debug section of the Settings)

**Closed as completed** 2024-01-02 15:27 UTC
Labels: enhancement
